import {
  Smartphone, Watch, Headphones, Laptop,
  Plug, Gamepad2, Home, Camera,
} from 'lucide-react';

export const categoryConfig = [
  {
    id: 'mobile-phones',
    name: 'Mobile Phones',
    slug: 'mobile-phones',
    icon: Smartphone,
    description: 'Flagship and everyday phones with cleaner premium selection.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&q=80',
  },
  {
    id: 'smart-watches',
    name: 'Smart Watches',
    slug: 'smart-watches',
    icon: Watch,
    description: 'Refined wearables for fitness, calls, and daily tracking.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80',
  },
  {
    id: 'earbuds',
    name: 'Earbuds',
    slug: 'earbuds',
    icon: Headphones,
    description: 'Immersive wireless audio with cleaner premium tuning.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80',
  },
  {
    id: 'laptops',
    name: 'Laptops',
    slug: 'laptops',
    icon: Laptop,
    description: 'Portable performance for creators, work, and everyday speed.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80',
  },
  {
    id: 'accessories',
    name: 'Accessories',
    slug: 'accessories',
    icon: Plug,
    description: 'Desk, charging, and carry essentials with a refined finish.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&q=80',
  },
  {
    id: 'gaming-gadgets',
    name: 'Gaming Gadgets',
    slug: 'gaming-gadgets',
    icon: Gamepad2,
    description: 'Performance-first gaming gear without the visual noise.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&q=80',
  },
  {
    id: 'smart-home',
    name: 'Smart Home',
    slug: 'smart-home',
    icon: Home,
    description: 'Connected home devices with a simpler and smarter feel.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80',
  },
  {
    id: 'cameras',
    name: 'Cameras',
    slug: 'cameras',
    icon: Camera,
    description: 'Capture-first tools for creators who care about detail.',
    count: 50,
    bg: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80',
  },
];
